[build]
  publish = "src/pages"

[[redirects]]
  from = "/dum01"
  to = "/dum01.html"
  status = 200

[[redirects]]
  from = "/dum02"
  to = "/dum02.html"
  status = 200

[[redirects]]
  from = "/dum03"
  to = "/dum03.html"
  status = 200

[[redirects]]
  from = "/dum04"
  to = "/dum04.html"
  status = 200
